docs(changelog): updated changelog for tag v0.3.3
tier4/CARET_doc pull request #113
Opened 2022-11-28 07:53 UTC by takam5f2

Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

2022-11-28 12:04 UTC, hsgwa requested changes

2022-11-28 12:04 UTC, hsgwa commented on docs/changelog.md
> +- Fixed a bug which makes wrong graphs ([CARET_analyze #201](https://github.com/tier4/CARET_analyze/pull/201))
Small point, but I think INCORRECT would be more appropriate in this case.
```suggestion
- Fixed a bug which makes incorrect graphs ([CARET_analyze #201](https://github.com/tier4/CARET_analyze/pull/201))
```

2022-11-28 12:04 UTC, hsgwa commented on docs/changelog.md
> +- Excluded JSON- and TOML-based file from targeted files to be checked by `check_caret_rclcpp` ([ros2caret #53](https://github.com/tier4/ros2caret/pull/53) and suppressed unnecessary warnings ([ros2c
```suggestion
- Suppressed unnecessary warnings in `check_caret_rclcpp`  ([ros2caret #53](https://github.com/tier4/ros2caret/pull/53), [ros2caret #54](https://github.com/tier4/ros2caret/pull/54))
```

2022-11-29 00:33 UTC, takam5f2 commented
@hsgwa  
Could you check this PR?

2022-11-29 01:26 UTC, hsgwa approved these changes
LGTM!

2022-11-29 01:26 UTC, merged