docs: improve visualization chapter
tier4/CARET_doc pull request #119
Opened 2022-12-01 02:39 UTC by takam5f2

2022-12-12 09:33 UTC, keita1523 reviewed
minor suggestion

2022-12-13 11:29 UTC, hsgwa requested changes

2022-12-13 11:29 UTC, hsgwa commented on docs/visualization/filter/lttng_event_filter.md
> +With `init_pass_filter` method, events recorded by initialization tracepoints are not loaded onto memory.
```suggestion
With `init_pass_filter` method, events recorded by runtime tracepoints are not loaded onto memory.
```

2022-12-13 11:29 UTC, hsgwa commented on docs/visualization/index.md
> +- [`create_communication_period_plot](./communication/index.md#period)
```suggestion
- [`create_communication_period_plot`](./communication/index.md#period)
```

2022-12-26 02:57 UTC, takam5f2 commented on docs/visualization/callback/index.md
> +The vertical axis means period of callback execution, labeled as `Period [ms]`. It is plotted per sample.
Fixed at https://github.com/tier4/CARET_doc/pull/119/commits/1d45655d8182a3bb9e13e99cc40340ddf5a32f24

2022-12-26 03:02 UTC, takam5f2 commented on docs/visualization/communication/publish_subscription.md
> +`Plot.create_publish_subscription_frequency_plot(Collection[publish: Publisher or subscription: Subscriber])` is introduced to check whether target publisher or frequency.
Fixed at https://github.com/tier4/CARET_doc/pull/119/commits/08af126e4cda672684d6cee88aecc0075ee6a66c

2022-12-26 03:02 UTC, takam5f2 commented on docs/visualization/communication/publish_subscription.md
> +This visualization show you when publish or subscription is invoked in a target application.
Fixed at https://github.com/tier4/CARET_doc/pull/119/commits/08af126e4cda672684d6cee88aecc0075ee6a66c

2022-12-26 03:03 UTC, takam5f2 commented on docs/visualization/callback/index.md
> +The vertical axis means period of callback execution, labeled as `Period [ms]`. It is plotted per sample.
@keita1523 
I'd like to resolve this comment. Please feel free to reopen this if you have an additional comment.

2022-12-26 03:04 UTC, takam5f2 commented on docs/visualization/communication/publish_subscription.md
> +This visualization show you when publish or subscription is invoked in a target application.
@keita1523
I'd like to resolve this comment. Please feel free to reopen this if you have an additional comment.

2022-12-26 03:04 UTC, takam5f2 commented on docs/visualization/communication/publish_subscription.md
> +`Plot.create_publish_subscription_frequency_plot(Collection[publish: Publisher or subscription: Subscriber])` is introduced to check whether target publisher or frequency.
@keita1523
I'd like to resolve this comment. Please feel free to reopen this if you have an additional comment.

2022-12-26 04:30 UTC, takam5f2 commented on docs/visualization/communication/index.md
> +CARET serves `Communication` class which focus on a topic message from a source node to a destination node. A `Communication`-based object is retrieved from method, `Application.get_communication('so
@hsgwa  
I understand what you mean. Does it seem good if I add `info` or `note` to tell that our intention is different from the current implementation?

2022-12-26 06:02 UTC, takam5f2 commented on docs/visualization/communication/many_to_many_communication.md
> +If you see that publish frequency is different from subscription frequency, you may think loss of topic messages. However, it is reasonable when many-to-1 communication is performed.
Added more explanation at https://github.com/tier4/CARET_doc/pull/119/commits/4a532050fc7c1109518d77b88c1b21c35b4f301c

2022-12-26 06:03 UTC, takam5f2 commented
@hsgwa @keita1523  
Thank you for reviewing this PR. I'd like to close this because this PR is carried to #131

2022-12-26 06:03 UTC, closed without merging