docs(configuration): add the explanation of Architecture.diff_* functions
tier4/CARET_doc pull request #168
Opened 2023-03-10 13:09 UTC by taro-yu

## Description
`Require differences of two architectures` is added to chapter Configuration of CARET_doc.
`Require differences of two architectures` section explains how to use `diff_XXX_YYY` function.

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-03-16 02:57 UTC, rokamu623 requested changes
As pointed out in the github action, it is `Architecture`, not `Architecure`.

2023-03-20 01:30 UTC, keita1523 requested changes

2023-03-20 01:30 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +In this setup, the `left_arch` has two nodes: `node1` and `node2`, and the `right_arch` has three nodes: `node1`, `node3` and `node4`. Therefore, the node name that `left_arch` and `right_arch` have
```suggestion
In this setup, the `left_arch` has two nodes: `node1` and `node2`, and the `right_arch` has three nodes: `node1`, `node3` and `node4`. 
The `left_arch` and `right_arch` have `node1` as common node.
```

2023-03-20 01:30 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +`diff_node_pubs()` and `diff_node_subs()` are functions that take nodes in an architecture and compare them. The nodes given can be two nodes in the same architecture or in two different architecture
```suggestion
Nodes consist of the node name, publish topic, and subscription topic.
The `diff_node_pubs()` and `diff_node_subs()` function find the publish and subscription topics that exist only in one of the two nodes. 

```

2023-03-20 03:21 UTC, keita1523 requested changes
Please apply this modification to other functions.

2023-03-20 03:21 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +An example of the use of `diff_topic_names()` is shown in `#sample_2`.
```suggestion
The function `diff_topics_names()` compares topic names of nodes.
```

2023-03-20 03:21 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +#('topic3', 'topic4')
```suggestion
# get difference topic names
left_only_topics, right_only_topics = Architecture.diff_topic_names(left_arch, right_arch)

# display differences
print(left_only_topics)
print(right_only_topics)
```

2023-03-20 03:21 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +Therefore, the topic name that only `left_arch` has is `topic2`, and the topic names that only `right_arch` has are `topic3` and `topic4`, which are the return value and output at the end of the scri
```suggestion
This function inputs two architectures, compares them, and outputs the topic names that exist only in one of nodes.
```

2023-03-20 03:24 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +`diff_node_pubs()` and `diff_node_subs()` are functions that take nodes in an architecture and compare them. The nodes given can be two nodes in the same architecture or in two different architecture
Don't need to apply this modification.
Please apply [here](https://github.com/tier4/CARET_doc/pull/168#pullrequestreview-1347730340).

2023-03-20 04:29 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +In this setup, the `left_arch` has two nodes: `node1` and `node2`, and the `right_arch` has three nodes: `node1`, `node3` and `node4`. Therefore, the node name that `left_arch` and `right_arch` have
Don't need to apply this modification.
Please apply [here](https://github.com/tier4/CARET_doc/pull/168#pullrequestreview-1347730340).

2023-03-20 08:27 UTC, taro-yu commented on docs/configuration/.pages
> +    - Differences of architectures: architecture_diff_func.md
Changed as above.

2023-03-20 08:27 UTC, taro-yu commented on docs/configuration/index.md
> +- [**Require differences of two architectures**](./architecture_diff_func.md) will tell you how to use `diff_XXX_YYY()` functions
Changed as above.

2023-03-20 09:29 UTC, keita1523 requested changes

2023-03-20 11:58 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +The diff function can be used to find the difference between two architectures. Specifically, the diff functions can find data that only exist in each, e.g. node name, pub/sub topic.
```suggestion
The diff function can be used to find the difference between two architectures. Specifically, the diff functions can find data that exist only in one of the architectures, such as node names, publish/subscribe topics, etc. 
```

2023-03-20 11:58 UTC, keita1523 commented on docs/configuration/architecture_diff_func.md
> +      The architecture object has other elements such as Executor and Callback. However, the functions that gets the difference of Executors or Callbacks are not yet implemented. Please contact the d
```suggestion
      The architecture object has other elements such as Executor and Callback. However, the functions that get the difference of Executors or Callbacks are not yet implemented. Please contact the developers if needed.
```

2023-03-20 12:36 UTC, keita1523 submitted a review, later dismissed
LGTM!
(Please pass pre-commit error)

2023-03-24 01:36 UTC, rokamu623 approved these changes
Sorry for the delay in approval.
LGTM!

2023-03-24 02:06 UTC, merged