add extend_path docs
tier4/CARET_doc pull request #172
Opened 2023-03-23 11:57 UTC by ymski

## Description

Add the document of Path analysis option, `include_first_callback` and `include_last_callback`.

## Related links
- https://github.com/tier4/CARET_analyze/pull/263

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-03-27 09:11 UTC, takeshi-iwanari requested changes
I added some suggestions. Please adopt them if you like it.

2023-03-27 09:11 UTC, takeshi-iwanari commented on docs/configuration/inter_node_data_path.md
> +  - If `True`, the time from callback_start to publish is included in the path analysis. The trace data used for the above callback_start adopts the data closest to the time of publish among those wi
```suggestion
  - If `True`, the processing time in the first node is included in the path analysis. The callback_start in the first node is that of a trace data whose timestamp is the closest to publish and thread id (tid) is the same as publish. Note that a callback object of the callback_start in the first node can vary if the node has several callbacks and any of them runs before publish.
```

2023-03-27 09:11 UTC, takeshi-iwanari commented on docs/configuration/inter_node_data_path.md
> +  - If `True`, the time from callback_start to callback_end is included in the path analysis.
```suggestion
  - If `True`, the processing time in the last node is included in the path analysis.
```

2023-03-27 09:11 UTC, takeshi-iwanari commented on docs/configuration/inter_node_data_path.md
> +- `callback_start` to `rclcpp_publish` or `rclcpp_intra_publish` in the first node.
```suggestion
- Processing time in the first node; from `callback_start` to `rclcpp_publish` or `rclcpp_intra_publish`
```

2023-03-27 09:11 UTC, takeshi-iwanari commented on docs/configuration/inter_node_data_path.md
> +- `callback_start` to `callback_end` in the last node.
```suggestion
- Processing time in the last node; from `callback_start` to `callback_end`
```

2023-03-28 02:35 UTC, ymski commented
@takeshi-iwanari 
Thank you for your review. The explanations you proposed were good, so I have adopted them as they are.

2023-03-28 04:32 UTC, takeshi-iwanari approved these changes
LGTM

2023-03-28 04:33 UTC, takeshi-iwanari commented
@ymski 
Thank you for working on it.
You can merge this PR by yourself.

2023-03-28 04:34 UTC, merged