docs: add description about histograms graph
tier4/CARET_doc pull request #221
Opened 2023-09-08 05:32 UTC by emori-ctc

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-09-08 05:49 UTC, rokamu623 requested changes
The following modification is proposed:

2023-09-08 05:49 UTC, rokamu623 commented on docs/visualization/latency/index.md
> +The horizontal axis means latency, labeled as `Latency [ms]`. The vertical axis is the Probability of delay, labeled as `probability`.
I would like to arrange it in the form of follow:

```The vertical axis is the probability of execution [hogehoge], labeled `probability`.```

2023-09-08 07:18 UTC, bopeng-saitama requested changes

2023-09-11 02:04 UTC, rokamu623 approved these changes
LGTM!

2023-09-11 02:07 UTC, bopeng-saitama approved these changes
LGTM

2023-09-20 05:28 UTC, nabetetsu approved these changes
LGTM :+1:

2023-09-20 06:18 UTC, merged