docs: add tracepoints and babeltrace description for user
tier4/CARET_doc pull request #26
Opened 2022-04-05 06:34 UTC by kuboichiTakahisa

2022-04-08 05:26 UTC, hsgwa requested changes
explain_measurement_methodの内容はユーザーにとっては細かすぎるので、
https://tier4.github.io/CARET_doc/pr-26/design/how_to_calculate_latency/
へ統合をお願いします。

Supplements側に書くのであれば、レイテンシの定義に対して補足して頂けますと助かります。

2022-04-11 00:41 UTC, hsgwa requested changes
「アドレス値を紐付ける」というのは中身の話で、ユーザーにとって細かい内容ですので、
explain_measurement_methodの内容はhow_to_calculate_latencyの方へ移動をお願いします。
そうすると内容の重複も出てくると思います。重複箇所は不要ですので削除をお願いします。

図がブラウザ上で見ると大きすぎるのが気になりました。
適度にリサイズをお願いします。

2022-04-12 06:05 UTC, kuboichiTakahisa commented
explain_measurement_methodの内容をhow_to_calculate_latencyへ移動し、重なっている内容を削除いたしました。
図の大きさを変更しましたが、このサイズでよろしいでしょうか？

2022-04-12 07:07 UTC, hsgwa requested changes

2022-06-24 02:38 UTC, hsgwa commented
@keita1523 
すみません、以前リポジトリの整理中の際に、ドキュメント更新用に１クッションとして https://github.com/keita1523/CARET_doc を挟むようにお願いしていたのですが、うまく修正＆反映が回せなくなってしまいました。

こちらのPRは余計な文章まで削除されていて、マージしようにもできない状態で止まっています。  
ドキュメントの追加等の差分は小分けにして、直接tier4/caret_docにPRを出すように変えて頂けないでしょうか？


1. 一旦、本PRへの[chore: add path_verify.md](https://github.com/tier4/CARET_doc/pull/26/commits/3e515c6c55fc961397afb2c86b1f8781b44ac09c) は差分から削除
2. [chore: add path_verify.md](https://github.com/tier4/CARET_doc/pull/26/commits/3e515c6c55fc961397afb2c86b1f8781b44ac09c)はtier4/caret_docに別PRとして送信
3. 以降のドキュメントの追加はtier4/caret_docにPR

2022-06-24 05:48 UTC, keita1523 commented
このPRの状況が追いきれないですね。
本PRは削除してcaret_docに直接追加したいと思います。

2022-06-27 13:44 UTC, closed without merging