E2Eレイテンシ計測方法の説明追加
tier4/CARET_doc pull request #3
Opened 2021-12-03 10:12 UTC by keita1523

E2Eレイテンシ測定方法の説明を追加しました。
説明がわかりにくい、間違ってる、見栄えが悪いなど、コメントを頂けると幸いです。
ご確認お願い致します。

2021-12-08 04:59 UTC, hsgwa requested changes
コメントしたので確認をお願いします。

2021-12-08 10:33 UTC, keita1523 commented on docs/index.md
> +  - [E2Eレイテンシ測定方法の説明](./supplements/explain_measurement_method.md)
pageに追加しました。

2021-12-08 10:34 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +| idx | callback_start (CB_A) [s] | rclcpp_publish (CB_A) [s] | callback_start (CB_B) [s] | rclcpp_publish (CB_B) [s] |
表の修正を行いました。

2021-12-08 11:00 UTC, keita1523 reviewed
@hsgwa 
懸念点があるところにコメントを追加しました。
お時間あるときに確認して頂きたいです。

2021-12-08 11:00 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +
引き算とう表現でよかったでしょうか。

2021-12-08 11:00 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +rclcpp_intra_publisherとdispatch_intra_process_subscription_callbackは同じmessage_argを持つトレースポイント同士で紐づけ、dispatch_intra_process_subscription_callbackとcallback_startは同じcallback_argを持つトレースポイント同士で紐づけることにより、下記
紐づけの説明はあっているでしょうか。

2021-12-08 11:00 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +> ※そのためSingle Threaded Executorでしか計算できません。
Singleしかできない、との因果関係はあっていますでしょうか。

2021-12-08 11:00 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +上記表のようにコールバックA・B（cb_A・cb_B）が存在し、A→Bと処理が続く時、コールバックチェーンは下記表のように一つのテーブルにできます。
表を用いて説明しましたが意味合い等あっていますでしょうか。
またわかりづらいなどの意見があれば頂きたいです。

2021-12-08 11:00 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +
想定・長所・短所は長谷川さんの文をそのまま貼り付けました。
問題ないでしょうか。

2021-12-08 11:00 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +入力トピックと出力トピックの時刻の差分からノードレイテンシを算出します。
説明としてあってますでしょうか。

2021-12-13 06:28 UTC, hsgwa commented on docs/supplements/explain_measurement_method.md
> +rclcpp_intra_publisherとdispatch_intra_process_subscription_callbackは同じmessage_argを持つトレースポイント同士で紐づけ、dispatch_intra_process_subscription_callbackとcallback_startは同じcallback_argを持つトレースポイント同士で紐づけることにより、下記
はい、合っております。

2021-12-13 06:28 UTC, hsgwa commented on docs/supplements/explain_measurement_method.md
> +
はい、あっています。

2021-12-13 06:32 UTC, hsgwa commented on docs/supplements/explain_measurement_method.md
> +> ※そのためSingle Threaded Executorでしか計算できません。
少し違いますね
callback_startとrclcpp_publishはそれぞれコールバックのインスタンスのアドレスと、publisherのインスタンスのアドレスを元に、対応するもの同士を紐付けています。
ですので、multi threaded executorでも算出はできます。

multi threaded executor で、かつmutually exclusive出ない場合（≒ reentrantの場合）には、
アドレスで紐付けても以下のようになってしまい、おかしな物同士がくっついてしまします。
1. callback_start() # lost 
2. callback_start() # 3.と紐付け
3. publish()
4. publish() # 無視

2021-12-13 06:36 UTC, hsgwa commented on docs/supplements/explain_measurement_method.md
> +入力トピックと出力トピックの時刻の差分からノードレイテンシを算出します。
もう少し説明を足して頂けますでしょうか？

> 入出力のヘッダーでマッチングを取り、入力トピックと出力トピックの時刻の差分からノードレイテンシを算出します。

とお願いします。

2021-12-13 06:39 UTC, hsgwa commented on docs/supplements/explain_measurement_method.md
> +上記表のようにコールバックA・B（cb_A・cb_B）が存在し、A→Bと処理が続く時、コールバックチェーンは下記表のように一つのテーブルにできます。
私の説明不足な気がしますが、
ノードレイテンシをコールバックチェーンで出す時は、
callback_start,とcallback_endで結合します。
rclcpp_publish (cb_A)→ callback_end (cb_A)に置き換えていただけますでしょうか？

cb_Bはpublichはそのまま必要です。

2021-12-13 06:40 UTC, hsgwa commented on docs/supplements/explain_measurement_method.md
> +
確認しました。問題ないです。

2021-12-13 06:41 UTC, hsgwa requested changes
コメントを追加しました。確認をお願いします。

2021-12-15 11:04 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +> ※そのためSingle Threaded Executorでしか計算できません。
こちら、知識として把握しておき、Singleしかできないという説明は消しておきます。

2021-12-15 11:20 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +入力トピックと出力トピックの時刻の差分からノードレイテンシを算出します。
修正しました。すみません。

2021-12-15 11:21 UTC, keita1523 commented on docs/supplements/explain_measurement_method.md
> +上記表のようにコールバックA・B（cb_A・cb_B）が存在し、A→Bと処理が続く時、コールバックチェーンは下記表のように一つのテーブルにできます。
@hsgwa 
こちら注釈に文章を追加しました。確認お願い致します。

2021-12-17 02:20 UTC, hsgwa approved these changes
確認しました。良さそうですのでマージします。

2021-12-17 02:20 UTC, merged