feature: add setup manual with ansible
tier4/CARET_doc pull request #30
Opened 2022-04-21 13:39 UTC by takam5f2

I'd like to add quick installation guide after merging https://github.com/tier4/caret/pull/7 is approved.

Signed-off-by: Takayuki AKAMINE <takayuki.akamine@tier4.jp>

2022-04-25 05:45 UTC, hsgwa requested changes

2022-04-25 05:45 UTC, hsgwa commented on docs/tutorials/setup.md
> +   ./setup_caret.bash
こちらは./setup_caret.shでは無いでしょうか？
確認お願いします。

2022-04-25 05:45 UTC, hsgwa commented on docs/tutorials/setup.md
> +ILTTng のインストール
**I** が冒頭に入っています。 ILTTng

2022-05-02 01:01 UTC, takam5f2 commented on docs/tutorials/setup.md
> +ILTTng のインストール
https://github.com/tier4/CARET_doc/pull/30/commits/b018d548b465a657926fa8af93c8b3ae1b040b57 で修正しました。

2022-05-02 01:01 UTC, takam5f2 commented on docs/tutorials/setup.md
> +   ./setup_caret.bash
https://github.com/tier4/CARET_doc/pull/30/commits/b018d548b465a657926fa8af93c8b3ae1b040b57 で修正しました。

2022-05-09 05:58 UTC, hsgwa approved these changes

2022-05-09 05:58 UTC, merged