fix build procedure
tier4/caret_doc pull request #322
Opened 2023-12-21 04:54 UTC by ymski

## Description
Fix build procedure.
When building with iron, CARET does not need to use caret-rclcpp.

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [x] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-12-22 01:30 UTC, isp-uetsuki approved these changes
LGTM

2023-12-22 02:11 UTC, isp-uetsuki requested changes

2023-12-22 02:11 UTC, isp-uetsuki commented on docs/tutorials/recording.md
Changed instructions cause error at `ros2 caret check_caret_rclcpp ~/ros2_ws/` because `~/ros2_caret_ws/install/local_setup.bash` is not sourced. I suggest adding "for iron" block under `ros2 caret check_caret_rclcpp ~/ros2_ws/` and indicating there is no need to run `ros2 caret check_caret_rclcpp`.

2023-12-25 06:35 UTC, ymski commented on docs/tutorials/recording.md
fixed in [fafbf0c](https://github.com/tier4/caret_doc/pull/322/commits/fafbf0ca0fd9a6c491cd189b3c34b36f6f5a1d77).

2023-12-25 06:44 UTC, isp-uetsuki approved these changes
LGTM

2023-12-25 06:48 UTC, merged