fix: latency visualize API new features in the Gallery section.
tier4/caret_doc pull request #332
Opened 2024-03-01 06:31 UTC by emori-ctc

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2024-03-05 03:27 UTC, rokamu623 requested changes
The combination with the graph itself (ex: Callback frequency graph) should be added to the bulleted list.

Replace "Other..." with a sentence meaning "These elements can be visualized".

2024-03-06 04:27 UTC, rokamu623 requested changes

2024-03-06 04:27 UTC, rokamu623 commented on docs/gallery.md
> +- Pub/Sub period
Path response time

2024-03-06 04:27 UTC, rokamu623 commented on docs/gallery.md
> +- Path frequency
Path frequency is not implemented.
```suggestion
- Path frequency
```

2024-03-06 04:27 UTC, rokamu623 commented on docs/gallery.md
> +- Path frequency
Path frequency is not implemented.
```suggestion
- Path frequency
```

2024-03-06 04:27 UTC, rokamu623 commented on docs/gallery.md
> +- Pub/Sub period
Path response time

2024-03-06 04:27 UTC, rokamu623 commented on docs/gallery.md
> +## [Callback Scheduling Visualization](./visualization/scheduling/callback.md)
Application | Executor | Path | Node | CallbackGroup | Sequence[CallbackGroup]

2024-03-07 06:47 UTC, rokamu623 requested changes

2024-03-07 06:47 UTC, rokamu623 commented on docs/gallery.md
> +### [callback latency graph](./visualization/latency/index.md)
```suggestion
### [Callback latency graph](./visualization/latency/index.md)
```

2024-03-07 06:47 UTC, rokamu623 commented on docs/gallery.md
> +### [Response time graph](./visualization/path/response_time.md)
```suggestion
### [Path response time graph](./visualization/path/response_time.md)
```

2024-03-07 08:01 UTC, rokamu623 approved these changes
LGTM!

2024-03-07 09:06 UTC, isp-uetsuki approved these changes
LGTM

2024-03-08 04:16 UTC, merged