docs: API to get callback info
tier4/CARET_doc pull request #55
Opened 2022-06-27 03:34 UTC by atsushi421

Signed-off-by: atsushi421 <a.yano.578@ms.saitama-u.ac.jp>

@hsgwa 
[コールバック単位の情報取得 API](https://tier4.atlassian.net/browse/T4PB-14876) に関するドキュメントを追加しました。
ご確認をお願いいたします。

2022-06-27 03:49 UTC, hsgwa requested changes

2022-06-27 03:49 UTC, hsgwa commented on docs/tips/gallery.md
> +CARET can visualize the execution frequency, jitter, and latency per unit time for each callback and obtain them in the pandas DataFrame format.
CARETを主語にするのなら、以下の方が適切かもしれません。確認をお願いします。

> CARET can visualize ~~ and obtain ~~.
> CARET can visualize ~~ and provide ~~.

2022-06-27 03:49 UTC, hsgwa commented on docs/tips/gallery.md
> +from caret_analyze import Architecture, Application, Lttng
以下の行も追加お願いします。
```
from caret_analyze.plot import Plot
```

2022-06-27 03:49 UTC, hsgwa commented on docs/tips/gallery.md
> +---Output in jupyter-notebook as below---
一応ここはpythonコードとして解釈されているので、#でコメントにお願いします。

2022-06-27 04:27 UTC, atsushi421 commented
@hsgwa 
ご指摘ありがとうございます。
修正させていただきました。

2022-06-27 06:28 UTC, hsgwa commented
@atsushi421 
他のPRをマージした関係で、コンフリクトが発生してしまいました。
お手数ですが修正をお願いできないでしょうか？
追加の修正は特になしです。

2022-06-28 06:19 UTC, hsgwa approved these changes
LGTM

2022-06-28 08:20 UTC, merged