docs: create_and_verify_architecture_file_with_CLI
tier4/CARET_doc pull request #70
Opened 2022-07-28 09:36 UTC by atsushi421

@hsgwa CC: @keita1523 
[ros2 caret の CLI でアーキテクチャファイルの作成・チェックを可能にする](https://tier4.atlassian.net/browse/T4PB-17111) に関するドキュメントを、CARET_doc の Tips に追加しましたので、ご確認をお願いいたします。

2022-08-01 05:56 UTC, hsgwa requested changes

2022-08-01 05:56 UTC, hsgwa commented on docs/tips/create_and_verify_architecture.md
> +The following commands can be used to create an architecture file that has minimum descriptions from trace data.
Architectureはminimum descriptionと言うよりは、静的な（実行毎に依らない）情報を持ったものです。
以下の表現ではいかがでしょうか？
```suggestion
The following commands can be used to create an architecture file that has application structure and latency definition.
```

2022-08-01 05:56 UTC, hsgwa commented on docs/tips/create_and_verify_architecture.md
> +The following command executes the `path.verify()` method on paths defined in the architecture file.
この文章を呼んだ後に、「path.verifyとはなに？」となってしまうので、
「path.verifyが行う内容」を書いたほうが良いと思います。
```suggestion
The following command verifies whether latency definitions are set sufficiently.
```

2022-08-01 05:56 UTC, hsgwa commented on docs/tips/create_and_verify_architecture.md
> +Please refer to [How to define latency of a single node](https://tier4.github.io/CARET_doc/latest/tutorials/configuration/#how-to-define-latency-of-a-single-node) for details on the `path.verify()` m
「このコマンドはverify() を実行しているのと同じです。verifyコマンドについてはこちらをン参照ください」というように、ここで初めてverify()を出すようにしてはいかがでしょうか？

2022-08-08 03:37 UTC, atsushi421 commented
@hsgwa 
指摘して頂いた事項を修正しましたので、ご確認をお願いいたします。

2022-08-08 09:39 UTC, hsgwa commented on docs/tips/create_and_verify_architecture.md
> +The following commands can be used to create a template architecture file including only the application structure section.
こちら細かいですが、architecture file templateにお願いします。

```suggestion
The following commands can create an architecture file template including only the application structure section.
```

2022-08-08 09:40 UTC, hsgwa requested changes
指摘箇所の対応をお願いします。

2022-08-08 23:54 UTC, atsushi421 commented
@hsgwa 
チェックありがとうございます。
ご指摘いただいた箇所を修正いたしました。
ご確認お願いいたします。

2022-08-10 07:13 UTC, hsgwa approved these changes
LGTM

2022-08-17 15:29 UTC, merged