docs: visualization section structure improvement
tier4/CARET_doc pull request #88
Opened 2022-10-03 00:20 UTC by bopeng-saitama

Signed-off-by: Bo Peng <82485734+bopeng-saitama@users.noreply.github.com>

Change the structure to one function one file.

Reform the gallery and add the source code location of each fuction.

Convert the Japanese present in the document to English.

2022-10-03 01:01 UTC, keita1523 requested changes
修正お願いします。

2022-10-03 04:37 UTC, hsgwa commented
treat_drop_as_delayはdeprecatedに変更予定ですので、ページは消す方向でお願いします。

2022-10-03 06:52 UTC, bopeng-saitama commented
> treat_drop_as_delayはdeprecatedに変更予定ですので、ページは消す方向でお願いします。 代わりにresponse timeを入れる予定です。

@hsgwa message_flow中のtreat_drop_as_delayの説明も不要でしょうか？

2022-10-04 07:21 UTC, hsgwa commented
> @hsgwa message_flow中のtreat_drop_as_delayの説明も不要でしょうか？

不要です。

2022-10-04 14:25 UTC, keita1523 commented on docs/visualization/trouble_shooting.md
> +    Execute the ros2_tracing command by pressing the Enter key to start, then it is necessary to execute the application to be measured.
後半が文章なのに、前半部が文章になってない（主語が無い）
統一してください

2022-10-05 13:41 UTC, bopeng-saitama commented
> Resolve conversationは三浦が押すので、ハンさんは押さないでください。

@keita1523 承知いたしました。指摘した問題点を修正しました。

2022-10-08 06:21 UTC, merged